### PR TITLE
Unify the couchbase setup for local dev and CI(github action)

### PR DESCRIPTION
**Pull request by xavierchow**
This PR is based on #4, it could be rebased if #4 gets some updates, the following are some improvements,
* use the [Dockerfile](https://github.com/xavierchow/clj-cb/blob/master/docker/couchbase/Dockerfile) as the single source of truth for the container.
* use docker-compose.
* 2 shell scripts to help to setup/teardown the couchbase container.
* use docker-compose within Github action steps as well.

### CODE REVIEW

**Comment by Alfrheim** [comment]
Thank you!

**Comment by xavierchow** [comment]
👍 , but the CI failed on the master, it seems the test is not stable(I see some timeout error from CI log...), you can try to re-run the CI or maybe I should check the test codes to see if there is a space to improve.

**Comment by Alfrheim** [comment]
Failed twice, let's try again :)
What bothers me is this one, I have the feeling I have seen one similar
**Exception in thread "cb-computations-6" java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.**

**Comment by fhitchen** [comment]
I looked at your docker-compose settings, I think you need to add the options I used in docker run to increase the CPU and memory allocated to the max allowed in the test environment.

options: --cpus 2 --memory 4GB

Two CPU's was the max I could allocate, I did not try to increase the memory beyond 4GB, but that might make the tests more predictable.

**Comment by Alfrheim** [comment]
Not sure where I need to put that... @fhitchen in your PR we had that in tthe github yml under services, but now we don't have services. Added directly in docker-compose didn't work (obviously :) ).
Checked that there are options to tell to docker-compose the memory and cpu's you can use, but not sure if that is how should work... any ideas?

**Comment by xavierchow** [comment]
Indeed there are some resource constraints options from the doc: https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu-and-other-resources,
but I'm not sure if we can get more resources from the GH action with them.
I also checked the test code, I found the related errors were from bucket-test, may I ask why do you remove/re-create the bucket for each test case? @Alfrheim 
https://github.com/Earthen/clj-cb/blob/dbd9c0c9c9ab477f8e68d160f07a9b7e3dfd6875/test/earthen/clj_cb/bucket_test.clj#L20

It seems it requires a warm-up for a new created bucket to become usable.
Screenshot 2020-01-13 21 17 53

If you are ok with reusing the same bucket for multiple test cases I could try to send a PR later.

**Comment by Alfrheim** [comment]
I don't remember sorry. But for the looks of it, maybe was to have a clean environment for each test? @xavierchow If you think that will help, go for it!

**Pull request merged**
